import { StyleSheet } from 'react-native';
import { colors, radius, shadows, spacing } from '@/theme';

export const styles = StyleSheet.create({
onboardingScreen: { flex: 1, backgroundColor: colors.background },
onboardingHeader: {
    height: 62,
    paddingHorizontal: 20,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: '#f8fbff',
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
  },
skipText: { color: '#697386', fontSize: 16, fontWeight: '700' },
onboardingBody: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 28,
    paddingTop: 26,
    paddingBottom: 18,
  },
onboardingBodyCompact: {
    paddingHorizontal: 28,
    paddingTop: 18,
    paddingBottom: 14,
  },
onboardingBodySecurity: {
    paddingTop: 18,
  },
onboardingContent: {
    width: '100%',
    alignItems: 'center',
    flexShrink: 1,
  },
onboardingContentCompact: {
    paddingTop: 0,
  },
onboardingContentSecurity: {
    paddingTop: 4,
  },
onboardingImagePlain: {
    minHeight: 198,
    alignItems: 'center',
    justifyContent: 'center',
  },
onboardingImageFrame: {
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.white,
    ...shadows.card,
  },
onboardingImageOne: { borderRadius: 7 },
onboardingImageTwo: {},
onboardingImageThree: {},
onboardingCopy: { alignItems: 'center', gap: 12 },
onboardingCopyWelcome: { marginTop: 28 },
onboardingCopyWorkflow: { marginTop: 30 },
onboardingCopyCompact: { marginTop: 22 },
onboardingCopySmall: { gap: 10, marginTop: 20 },
onboardingTitle: {
    color: '#1b202c',
    fontWeight: '800',
    textAlign: 'center',
    width: '100%',
  },
onboardingDescription: {
    color: '#4b5565',
    fontWeight: '400',
    textAlign: 'center',
    width: '100%',
    maxWidth: 280,
  },
onboardingFeatureRow: {
    width: '100%',
    flexDirection: 'row',
    gap: 14,
    marginTop: 24,
  },
onboardingFeatureRowCompact: {
    marginTop: 18,
  },
onboardingFeatureCard: {
    flex: 1,
    height: 70,
    borderRadius: 10,
    backgroundColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    ...shadows.card,
  },
onboardingFeatureText: { color: '#4b5565', fontSize: 12, fontWeight: '700' },
onboardingFooter: {
    width: '100%',
    gap: 18,
  },
onboardingFooterCompact: {
    gap: 14,
  },
onboardingDots: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
onboardingDot: { width: 7, height: 7, borderRadius: radius.full, backgroundColor: '#bfc8d8' },
onboardingDotActive: { width: 22, backgroundColor: colors.primary },
onboardingButton: {
    height: 48,
    borderRadius: 8,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
    ...shadows.button,
  },
onboardingButtonText: { color: colors.white, fontSize: 16, fontWeight: '700' },
center: { textAlign: 'center' },
authScreen: { justifyContent: 'center', minHeight: '100%' },
centerBlock: { alignItems: 'center', gap: spacing.sm },
loginTitle: { color: colors.text, fontSize: 30, lineHeight: 38, fontWeight: '800' },
rightLink: { color: colors.primary, textAlign: 'right' },
segment: { flexDirection: 'row', padding: spacing.xs, borderRadius: radius.md, backgroundColor: colors.graySoft },
segmentItem: { flex: 1, alignItems: 'center', padding: spacing.sm, borderRadius: radius.sm },
segmentActive: { backgroundColor: colors.primary },
segmentTextActive: { color: colors.white },
homeContainer: {
    paddingTop: spacing.xs, // Minimal top gap
    paddingBottom: 40,
  },
ordersStatsGrid: {
    gap: spacing.md,
    marginTop: spacing.md,
  },
statCardLarge: {
    padding: spacing.md,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: '#f1f5f9',
  },
statHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
statTitle: {
    fontSize: 12,
    fontWeight: '700',
    color: '#64748b',
    textTransform: 'none',
  },
statIconBadge: {
    width: 34,
    height: 34,
    borderRadius: 8,
    backgroundColor: '#eff6ff',
    alignItems: 'center',
    justifyContent: 'center',
  },
statValueLarge: {
    fontSize: 32,
    fontWeight: '800',
    color: '#0f172a',
    marginTop: 8,
  },
statRowSmall: {
    flexDirection: 'row',
    gap: spacing.md,
  },
statCardSmall: {
    flex: 1,
    padding: spacing.md,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: '#f1f5f9',
  },
statValueSmall: {
    fontSize: 22,
    fontWeight: '800',
    color: '#0f172a',
    marginTop: 4,
  },
createBtn: {
    marginTop: spacing.lg,
    backgroundColor: '#1d63d2',
    height: 48,
    borderRadius: 8,
  },
filterBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: '#f1f5f9',
    borderRadius: 8,
  },
filterBtnText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#64748b',
  },
paginationContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: spacing.lg,
    marginTop: spacing.xl,
    marginBottom: spacing.xxl,
  },
pageArrow: {
    width: 36,
    height: 36,
    borderRadius: 8,
    backgroundColor: '#f1f5f9',
    alignItems: 'center',
    justifyContent: 'center',
  },
pageNumbers: {
    flexDirection: 'row',
    gap: 8,
  },
pageNumber: {
    width: 32,
    height: 32,
    borderRadius: 8,
    backgroundColor: '#f1f5f9',
    alignItems: 'center',
    justifyContent: 'center',
  },
pageActive: {
    backgroundColor: '#0a49a8',
  },
pageText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#64748b',
  },
pageTextActive: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.white,
  },
sectionTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: spacing.sm,
  },
sectionTitle: {
    fontSize: 16,
    color: '#1e293b',
  },
fieldLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: '#64748b',
    marginBottom: 6,
    letterSpacing: 0.5,
  },
fieldRow: {
    gap: 2,
    paddingVertical: 10,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#e2e8f0',
  },
topRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    marginBottom: 12,
  },
datePicker: {
    height: 44,
    backgroundColor: '#f1f5f9',
    borderRadius: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 12,
  },
picker: {
    height: 44,
    backgroundColor: '#f1f5f9',
    borderRadius: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 12,
  },
subSection: {
    marginTop: spacing.md,
  },
requirementLabel: {
    marginTop: 12,
    marginBottom: 10,
  },
radioRow: {
    flexDirection: 'row',
    gap: 20,
  },
radioItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
radioCircle: {
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 2,
    borderColor: '#cbd5e1',
  },
radioActive: {
    borderColor: '#0a49a8',
    borderWidth: 5,
  },
priorityContainer: {
    paddingHorizontal: spacing.md,
    marginTop: spacing.md,
  },
priorityRow: {
    flexDirection: 'row',
    gap: spacing.md,
    marginTop: 12,
  },
priorityBtn: {
    flex: 1,
    height: 80,
    borderRadius: 12,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: '#f1f5f9',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
priorityNormalActive: {
    backgroundColor: '#eff6ff',
    borderColor: '#3b82f6',
  },
priorityUrgentActive: {
    backgroundColor: '#fef2f2',
    borderColor: '#ef4444',
  },
priorityBtnText: {
    fontSize: 12,
    color: '#64748b',
  },
figmaUploadBox: {
    height: 140,
    borderWidth: 1,
    borderColor: '#cbd5e1',
    borderStyle: 'dashed',
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: '#f8fafc',
  },
uploadCircle: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#eff6ff',
    alignItems: 'center',
    justifyContent: 'center',
  },
uploadMainText: {
    color: '#0a49a8',
    fontSize: 15,
  },
fileItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    padding: 12,
    backgroundColor: '#f1f5f9',
    borderRadius: 10,
    marginTop: spacing.sm,
  },
fileIcon: {
    width: 32,
    height: 32,
    borderRadius: 6,
    backgroundColor: '#fef2f2',
    alignItems: 'center',
    justifyContent: 'center',
  },
fileName: {
    fontSize: 13,
    color: '#1e293b',
  },
detailsMainCard: {
    padding: spacing.md,
    gap: spacing.md,
  },
detailsHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 4,
  },
detailsOrderNum: {
    fontSize: 22,
    fontWeight: '800',
    color: '#0a49a8',
  },
detailField: {
    gap: 4,
  },
detailLabel: {
    fontSize: 10,
    fontWeight: '700',
    color: '#64748b',
    letterSpacing: 0.5,
  },
detailValueRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
detailIcon: {
    width: 20,
    alignItems: 'center',
  },
detailValue: {
    fontSize: 16,
    color: '#1e293b',
  },
specialInstructionBox: {
    flexDirection: 'row',
    gap: 12,
    padding: 14,
    backgroundColor: '#eff6ff',
    borderRadius: 12,
    marginHorizontal: spacing.md,
    marginTop: spacing.md,
    borderWidth: 1,
    borderColor: '#dbeafe',
  },
instructionText: {
    fontSize: 13,
    color: '#1e3a8a',
    marginTop: 4,
    lineHeight: 18,
  },
engagementCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    padding: 14,
    marginHorizontal: spacing.md,
    marginTop: spacing.md,
    backgroundColor: '#f8fbff',
  },
engagementIconBox: {
    width: 44,
    height: 44,
    borderRadius: 8,
    backgroundColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#f1f5f9',
  },
engagementSub: {
    fontSize: 12,
    fontWeight: '600',
  },
engagementTitle: {
    fontSize: 15,
    color: '#1e293b',
  },
detailsSection: {
    paddingHorizontal: spacing.md,
    marginTop: spacing.lg,
  },
detailsSectionTitle: {
    fontSize: 16,
    color: '#1e293b',
    marginBottom: 12,
  },
notaryProfileCard: {
    padding: spacing.md,
  },
notaryInfoLarge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
  },
notaryAvatarBox: {
    position: 'relative',
  },
notaryAvatarLg: {
    width: 56,
    height: 56,
    borderRadius: 10,
  },
onlineDot: {
    position: 'absolute',
    bottom: -2,
    right: -2,
    width: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: colors.success,
    borderWidth: 2,
    borderColor: colors.white,
  },
notaryNameLg: {
    fontSize: 16,
    color: '#1e293b',
  },
ratingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 4,
  },
ratingText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#eab308',
  },
viewProfileBtn: {
    marginTop: 14,
    height: 40,
    borderRadius: 8,
    backgroundColor: '#f1f5f9',
    alignItems: 'center',
    justifyContent: 'center',
  },
viewProfileText: {
    fontSize: 13,
    color: '#0a49a8',
  },
sectionHeaderWithCount: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
fileCardDetails: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    padding: 12,
  },
fileIconBox: {
    width: 40,
    height: 40,
    borderRadius: 8,
    backgroundColor: '#fef2f2',
    alignItems: 'center',
    justifyContent: 'center',
  },
downloadBtn: {
    width: 36,
    height: 36,
    borderRadius: 8,
    backgroundColor: '#f1f5f9',
    alignItems: 'center',
    justifyContent: 'center',
  },
statusCard: {
    padding: spacing.md,
  },
logCard: {
    padding: spacing.md,
  },
logItem: {
    flexDirection: 'row',
    gap: 12,
  },
logIconBox: {
    width: 32,
    height: 32,
    borderRadius: 6,
    backgroundColor: '#eff6ff',
    alignItems: 'center',
    justifyContent: 'center',
  },
logHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 4,
  },
logDivider: {
    height: 1,
    backgroundColor: '#f1f5f9',
    marginVertical: 14,
  },
// Common Screen Elements
  pageHeader: {
    marginTop: 20,
    marginBottom: 4,
  },
pageTitle: {
    fontSize: 24,
    fontWeight: '800',
    color: '#0f172a',
    letterSpacing: -0.3,
    lineHeight: 30,
  },
pageSubtitle: {
    fontSize: 14,
    color: '#64748b',
    marginTop: 4,
    lineHeight: 20,
  },
sectionHeader: {
    marginTop: 24,
    marginBottom: 12,
  },
// Search & Filters
  searchContainer: {
    marginTop: 16,
    position: 'relative',
  },
searchBox: {
    marginBottom: 0,
  },
searchInput: {
    paddingLeft: 42,
    backgroundColor: '#f8fafc',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    height: 46,
    borderRadius: 12,
    fontSize: 14,
  },
searchIcon: {
    position: 'absolute',
    left: 14,
    top: 14,
    zIndex: 1,
  },
filterRow: {
    flexDirection: 'row',
    marginTop: 14,
    gap: 10,
    alignItems: 'center',
  },
// Document & Team Lists
  documentList: {
    gap: 16,
    marginTop: 20,
  },
listFooter: {
    marginTop: 32,
    alignItems: 'center',
    gap: 12,
    paddingBottom: 40,
  },
resultsCount: {
    fontSize: 13,
  },
// Card Margins
  formCard: {
    marginTop: 24,
  },
loadMoreBtn: {
    backgroundColor: '#f1f5f9',
    width: 140,
    height: 40,
    borderRadius: 8,
  },
loadMoreText: {
    color: '#334155',
    fontSize: 14,
    fontWeight: '700',
  },
filterBtnActive: {
    backgroundColor: '#0a49a8',
    borderColor: '#0a49a8',
  },
filterBtnTextActive: {
    color: colors.white,
  },
clearBtn: {
    paddingHorizontal: 8,
    paddingVertical: 8,
    justifyContent: 'center',
  },
clearBtnText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#0a49a8',
  },
// Document View specific
  previewContainer: {
    height: 320,
    backgroundColor: '#f8fafc',
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
  },
previewContent: {
    width: 200,
    height: 260,
    backgroundColor: colors.white,
    borderRadius: 4,
    ...shadows.card,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
    position: 'relative',
  },
mockDocLayer: {
    position: 'absolute',
    top: 20,
    left: 20,
    right: 20,
    bottom: 20,
    gap: 8,
  },
mockDocTitle: { height: 12, width: '40%', backgroundColor: '#f1f5f9', borderRadius: 2 },
mockDocLine: { height: 6, width: '90%', backgroundColor: '#f8fafc', borderRadius: 2 },
mockDocGrid: { flexDirection: 'row', gap: 10, marginTop: 10 },
mockDocBox: { flex: 1, height: 40, backgroundColor: '#f8fafc', borderRadius: 2 },
previewControls: {
    position: 'absolute',
    bottom: 20,
    width: '100%',
    alignItems: 'center',
  },
zoomPill: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(30, 41, 59, 0.9)', // Dark slate translucent
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 10,
    gap: 12,
  },
zoomBtn: { color: '#fff', fontSize: 20, fontWeight: '300' },
zoomText: { color: '#fff', fontSize: 13, fontWeight: '600' },
zoomDivider: { width: 1, height: 16, backgroundColor: 'rgba(255,255,255,0.2)' },
viewActionRow: {
    flexDirection: 'row',
    gap: 16,
    marginTop: 20,
  },
viewDownloadBtn: { flex: 1, backgroundColor: '#0a49a8' },
viewPrintBtn: { flex: 1, backgroundColor: colors.white, borderColor: '#e2e8f0' },
infoCard: {
    marginTop: 16,
    padding: 14,
    gap: 12,
  },
infoCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
infoCardTitle: {
    fontSize: 16,
    color: '#0a49a8',
  },
fieldGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.md,
  },
fieldFull: { width: '100%', gap: 4 },
fieldHalf: { width: '45%', gap: 4 },
fieldValue: { fontSize: 15, color: '#1e293b' },
uploadedByRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginTop: 2,
  },
userAvatarSm: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#eff6ff',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#dbeafe',
  },
userAvatarText: { fontSize: 10, fontWeight: '700', color: '#0a49a8' },
activityTimeline: {
    gap: 0,
    marginTop: 4,
  },
activityItem: {
    flexDirection: 'row',
    minHeight: 80,
  },
activityLeft: {
    width: 30,
    alignItems: 'center',
  },
activityIcon: {
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 2,
  },
activityLine: {
    position: 'absolute',
    top: 24,
    bottom: 0,
    width: 2,
    backgroundColor: '#f1f5f9',
    zIndex: 1,
  },
activityRight: {
    flex: 1,
    paddingLeft: 10,
    paddingBottom: 20,
  },
activityHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
activityTitle: {
    fontSize: 14,
    color: '#1e293b',
  },
activitySub: {
    fontSize: 12,
    color: '#64748b',
    marginTop: 2,
  },
activityTime: {
    fontSize: 10,
    fontWeight: '700',
    color: '#94a3b8',
    marginTop: 6,
    textTransform: 'uppercase',
  },
preview: { minHeight: 260, borderRadius: radius.lg, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border },
zoomBar: { position: 'absolute', bottom: spacing.lg, backgroundColor: colors.text, borderRadius: radius.full, paddingHorizontal: spacing.lg, paddingVertical: spacing.sm },
roleCards: { flexDirection: 'row', gap: spacing.md },
roleCard: { flex: 1, gap: spacing.sm },
checkRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm },
navRow: { minHeight: 54, borderRadius: radius.lg, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, padding: spacing.lg, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
calendar: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm },
dayCell: { width: '12%', textAlign: 'center' },
dateCell: { width: '12%', aspectRatio: 1, borderRadius: radius.full, alignItems: 'center', justifyContent: 'center' },
dateSelected: { backgroundColor: colors.primary },
dateSelectedText: { color: colors.white, fontWeight: '700' },
timeGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.md },
chatScreen: { minHeight: '100%' },
chatHeader: { flexDirection: 'row', alignItems: 'center', gap: spacing.md, borderBottomWidth: 1, borderColor: colors.border, paddingBottom: spacing.md },
avatarDark: { width: 38, height: 38, borderRadius: radius.full, backgroundColor: colors.text, alignItems: 'center', justifyContent: 'center' },
messageInput: { marginTop: 'auto', minHeight: 48, borderRadius: radius.md, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, flexDirection: 'row', alignItems: 'center', paddingHorizontal: spacing.md, gap: spacing.md },
// Team Screen specific
  teamAddBtn: {
    marginTop: 20,
    backgroundColor: '#1d63d2',
    height: 50,
    borderRadius: 12,
  },
dropdownBtn: {
    flex: 1,
    height: 44,
    backgroundColor: '#f1f5f9',
    borderRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
dropdownText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#334155',
  },
memberList: {
    gap: spacing.md,
    marginTop: spacing.md,
  },
// Add Member specific
  formSection: {
    marginTop: 20,
    gap: 12,
  },
formSectionLabel: {
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.5,
    marginBottom: 12,
  },
roleSelectionSection: {
    marginTop: 32,
  },
roleRow: {
    flexDirection: 'row',
    gap: 12,
  },
roleSelectCard: {
    flex: 1,
    padding: 14,
    gap: 8,
    position: 'relative',
  },
roleSelectCardActive: {
    borderColor: '#0a49a8',
    backgroundColor: '#fff',
    borderWidth: 2,
  },
roleIconBox: {
    width: 44,
    height: 44,
    borderRadius: 8,
    backgroundColor: '#f1f5f9',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 4,
  },
roleIconBoxActive: {
    backgroundColor: '#eff6ff',
  },
roleCardTitle: {
    fontSize: 16,
    color: '#64748b',
  },
roleCardTitleActive: {
    color: '#0a49a8',
  },
roleCardDesc: {
    fontSize: 11,
    lineHeight: 15,
  },
roleCheckCircle: {
    position: 'absolute',
    top: 10,
    right: 10,
  },
permissionsCard: {
    marginTop: 24,
    padding: 16,
    backgroundColor: '#f8fafc',
    gap: 12,
  },
permissionsTitle: {
    fontSize: 13,
    color: '#0a49a8',
    marginBottom: 4,
  },
checkBox: {
    width: 22,
    height: 22,
    borderRadius: 4,
    borderWidth: 2,
    borderColor: '#cbd5e1',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.white,
  },
checkBoxActive: {
    backgroundColor: '#0a49a8',
    borderColor: '#0a49a8',
  },
checkLabel: {
    fontSize: 15,
    color: '#1e293b',
  },
inviteToggleCard: {
    marginTop: 16,
    padding: 14,
  },
inviteToggleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
inviteIconBox: {
    width: 36,
    height: 36,
    borderRadius: 8,
    backgroundColor: '#f1f5f9',
    alignItems: 'center',
    justifyContent: 'center',
  },
inviteText: {
    flex: 1,
    fontSize: 15,
    color: '#334155',
  },
toggleSwitch: {
    width: 46,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#0a49a8',
    padding: 2,
  },
toggleKnob: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: colors.white,
    alignSelf: 'flex-end',
  },
formActions: {
    marginTop: 32,
    gap: 16,
  },
addMemberBtn: {
    backgroundColor: '#0a49a8',
    height: 54,
    borderRadius: 12,
  },
cancelLink: {
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
cancelLinkText: {
    color: '#64748b',
    fontSize: 15,
  },
});
