import { StyleSheet } from 'react-native';
import { shadows } from '@/theme';

export const notaryStyles = StyleSheet.create({
header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 12,
  },
statCard: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 10,
    gap: 12,
    marginBottom: 6,
  },
iconBox: {
    width: 34,
    height: 34,
    borderRadius: 9,
    alignItems: 'center',
    justifyContent: 'center',
  },
statTextContent: {
    flex: 1,
    gap: 1,
  },
statLabel: {
    fontSize: 13,
    color: '#1e293b',
  },
statValueLarge: {
    fontSize: 20,
    fontWeight: '800',
    color: '#0f172a',
  },
sectionTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 16,
    marginBottom: 10,
  },
liveBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f1f5f9',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 20,
    gap: 5,
  },
dot: {
    width: 5,
    height: 5,
    borderRadius: 2.5,
    backgroundColor: '#ef4444',
  },
orderCard: {
    padding: 12,
    marginBottom: 10,
    gap: 12,
  },
orderTop: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
initialsAvatar: {
    width: 34,
    height: 34,
    borderRadius: 9,
    alignItems: 'center',
    justifyContent: 'center',
  },
orderClientName: {
    fontSize: 15,
    color: '#0f172a',
  },
orderInfoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
infoItem: {
    flexDirection: 'row',
    gap: 8,
    alignItems: 'center',
  },
orderFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: '#f1f5f9',
  },
avatarGroup: {
    flexDirection: 'row',
  },
miniAvatar: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: '#fff',
  },
viewDetailsBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
viewDetailsText: {
    fontSize: 11,
    color: '#0a49a8',
    letterSpacing: 0.4,
  },
statusRefCard: {
    backgroundColor: '#f8fafc',
    borderRadius: 16,
    padding: 20,
    gap: 20,
  },
statusRefItem: {
    flexDirection: 'row',
    gap: 12,
  },
statusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    marginTop: 6,
  },
tabContainer: {
    flexDirection: 'row',
    backgroundColor: '#fff',
    marginTop: 16,
    padding: 3,
    borderRadius: 10,
    gap: 3,
  },
tabItem: {
    flex: 1,
    paddingVertical: 8,
    alignItems: 'center',
    borderRadius: 7,
  },
tabItemActive: {
    backgroundColor: '#0a49a8',
  },
tabText: {
    fontSize: 11,
    color: '#64748b',
  },
tabTextActive: {
    color: '#fff',
  },
detailsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 12,
  },
timelineItem: {
    flexDirection: 'row',
    gap: 16,
  },
timelineLeft: {
    alignItems: 'center',
  },
timelineDot: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#e2e8f0',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1,
  },
timelineActiveInner: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#1d4ed8',
  },
timelineLine: {
    width: 2,
    flex: 1,
    backgroundColor: '#f1f5f9',
    marginVertical: 4,
  },
infoStrip: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 14,
    gap: 12,
  },
iconCircle: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
scheduleLink: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 24,
    paddingVertical: 4,
  },
docItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    gap: 16,
  },
dateCell: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
  },
dateCellActive: {
    backgroundColor: '#1d4ed8',
    ...shadows.button,
  },
dateText: {
    fontSize: 14,
    color: '#334155',
  },
timeButton: {
    width: '31%',
    height: 42,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fff',
  },
timeButtonActive: {
    borderColor: '#2563eb',
    backgroundColor: '#eff6ff',
  },
timeButtonText: {
    fontSize: 13,
    color: '#475569',
  },
floatingChat: {
    position: 'absolute',
    bottom: 24,
    right: 20,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#0a49a8',
    alignItems: 'center',
    justifyContent: 'center',
    ...shadows.lg,
  },
onlineDotSmall: {
    position: 'absolute',
    top: 0,
    right: 4,
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#22c55e',
    borderWidth: 2,
    borderColor: '#0a49a8',
  },
chatHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
    backgroundColor: '#fff',
  },
onlineDot: {
    position: 'absolute',
    bottom: -2,
    right: -2,
    width: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: '#22c55e',
    borderWidth: 3,
    borderColor: '#fff',
  },
phoneCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
chatMsgWrapper: {
    marginBottom: 24,
  },
chatBubble: {
    maxWidth: '85%',
    padding: 14,
    borderRadius: 14,
  },
adminBubble: {
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#f1f5f9',
    borderTopLeftRadius: 4,
  },
userBubble: {
    backgroundColor: '#0a49a8',
    borderTopRightRadius: 4,
    ...shadows.sm,
  },
chatText: {
    fontSize: 14,
    lineHeight: 20,
    color: '#334155',
  },
dateDivider: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 32,
  },
dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: '#f1f5f9',
  },
chatInputArea: {
    padding: 14,
    paddingBottom: 28,
    backgroundColor: '#fff',
    borderTopWidth: 1,
    borderTopColor: '#f1f5f9',
  },
chatInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f8fafc',
    borderRadius: 10,
    paddingHorizontal: 8,
    height: 48,
  },
chatTextInput: {
    flex: 1,
    fontSize: 14,
    color: '#1e293b',
    paddingHorizontal: 10,
  },
sendCircle: {
    width: 36,
    height: 36,
    borderRadius: 9,
    backgroundColor: '#0a49a8',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
